# Generated by Django 5.0 on 2023-12-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("cancelled", "Cancelled")],
                default="active",
                max_length=10,
            ),
        ),
    ]
